CREATE TABLE "exposition" (
  "id" int primary key generated by default as identity,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp,
  "name" varchar(512) NOT NULL,
  "description" varchar(1024) NOT NULL,
  "status" char(1) NOT NULL,
  "miniature_url" varchar(2048) NOT NULL
);

CREATE TABLE "panel" (
  "id" int primary key generated by default as identity,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp,
  "exposition_id" int NOT NULL,
  "author_id" int NOT NULL,
  "name" varchar(512) NOT NULL,
  "status" char(1) NOT NULL,
  "miniature_url" varchar(2048) NOT NULL
);

CREATE TABLE "element" (
  "id" int primary key generated by default as identity,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp,
  "work_id" int NOT NULL,
  "panel_id" int NOT NULL,
  "title" varchar(512),
  "type" char(1) NOT NULL,
  "content" varchar(1024)
);

CREATE TABLE "work" (
  "id" int primary key generated by default as identity,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp,
  "author_id" int NOT NULL,
  "title" varchar(512),
  "type" char(1) NOT NULL,
  "content" varchar(2048) NOT NULL
);

CREATE TABLE "profile" (
  "id" int primary key generated by default as identity,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp,
  "username" varchar(256) NOT NULL
);

CREATE TABLE "contact" (
  "id" int primary key generated by default as identity,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp,
  "profile_id" int NOT NULL,
  "channel" varchar(128) NOT NULL,
  "name" varchar(256) NOT NULL,
  "url" varchar(2048) NOT NULL
);

CREATE TABLE "invite" (
  "id" int primary key generated by default as identity,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp,
  "panel_id" int NOT NULL,
  "invitee_id" int NOT NULL,
  "status" char(1) NOT NULL
);

CREATE TABLE "report" (
  "id" int primary key generated by default as identity,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp,
  "exposition_id" int NOT NULL,
  "profile_id" int NOT NULL,
  "description" varchar(1024) NOT NULL
);

ALTER TABLE "panel" ADD FOREIGN KEY ("exposition_id") REFERENCES "exposition" ("id");

ALTER TABLE "panel" ADD FOREIGN KEY ("author_id") REFERENCES "profile" ("id");

ALTER TABLE "element" ADD FOREIGN KEY ("panel_id") REFERENCES "panel" ("id");

ALTER TABLE "element" ADD FOREIGN KEY ("work_id") REFERENCES "work" ("id");

ALTER TABLE "report" ADD FOREIGN KEY ("exposition_id") REFERENCES "exposition" ("id");

ALTER TABLE "report" ADD FOREIGN KEY ("profile_id") REFERENCES "profile" ("id");

ALTER TABLE "invite" ADD FOREIGN KEY ("panel_id") REFERENCES "panel" ("id");

ALTER TABLE "invite" ADD FOREIGN KEY ("invitee_id") REFERENCES "profile" ("id");

ALTER TABLE "work" ADD FOREIGN KEY ("author_id") REFERENCES "profile" ("id");

ALTER TABLE "contact" ADD FOREIGN KEY ("profile_id") REFERENCES "profile" ("id");
